const store = require('../../utils/demoStore');
Page({
  onReady() { this.setData({ safeTop: (wx.getWindowInfo ? wx.getWindowInfo().statusBarHeight : wx.getSystemInfoSync().statusBarHeight) || 20 }); },
  data: { book: null, entries: [], index: 0, selected: -1, answered: false, showAnswer: false, showExample: false, awaitingNext: false, attempts: 0 },
  onLoad(options) { this.bookId = options.id || 'cet4'; this.reviewStart = (store.state.bookReviewResults[this.bookId] || []).length; const book = store.findBook(this.bookId); const entries = book.entries.map(entry => Object.assign({}, entry, { options: [entry.zh, '逐渐减少；拒绝', '支持；维持', '复杂的；困难的'] })); this.setData({ book, entries }); },
  get current() { return this.data.entries[this.data.index] || {}; },
  choose(e) { if (this.data.answered) return; const selected = Number(e.currentTarget.dataset.index); const current = this.data.entries[this.data.index]; const attempts = this.data.attempts + 1; const correct = selected === 0; if (!correct && attempts === 1) { this.setData({ selected, answered: true, showAnswer: false, showExample: true, awaitingNext: false, attempts }); return; } if (!correct && attempts >= 2) { store.saveBookReviewResult(this.bookId, current, false, attempts); this.setData({ selected, answered: true, showAnswer: false, showExample: false, awaitingNext: true, attempts }); wx.navigateTo({ url: '/pages/demo/detail?id=' + current.id + '&source=public&fromReview=1' }); return; } store.saveBookReviewResult(this.bookId, current, true, attempts); this.setData({ selected, answered: true, showAnswer: false, showExample: false, awaitingNext: true, attempts }); },
  unknown() { if (this.data.answered) return; const current = this.data.entries[this.data.index]; const attempts = this.data.attempts + 1; if (attempts === 1) { this.setData({ selected: -1, answered: true, showAnswer: false, showExample: true, awaitingNext: false, attempts }); return; } store.saveBookReviewResult(this.bookId, current, false, attempts); this.setData({ selected: -1, answered: true, showAnswer: false, showExample: false, awaitingNext: true, attempts }); wx.navigateTo({ url: '/pages/demo/detail?id=' + current.id + '&source=public&fromReview=1' }); },
  next() { if (!this.data.answered) return; if (this.data.showExample) { this.setData({ answered: false, showAnswer: false, showExample: false, awaitingNext: false, selected: -1, attempts: 1 }); return; } const next = this.data.index + 1; if (next >= this.data.entries.length) { wx.redirectTo({ url: '/pages/demo/review-recap?book=' + this.bookId + '&start=' + this.reviewStart }); return; } this.setData({ index: next, selected: -1, answered: false, showAnswer: false, showExample: false, awaitingNext: false, attempts: 0 }); },
  goBack() { wx.navigateBack({ delta: 1 }); }
});
